 --- 
 - name: Configure hosts & deploy application # <-- Словесное описание сценария (name)   
   hosts:all # <-- Для каких хостов будут выполняться описанные ниже таски(hosts)   
   tasks: # <-- Блоктасков (заданий), которые будут выполняться для данных хостов
     - name: Change mongo config file       
       become: true # <-- Выполнить задание от root       
       template: 
         src:templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона         
         dest: /etc/mongod.conf # <-- Путь на удаленном хосте   
         mode:0644 # <-- Права на файл, которые нужно установить
         
